spring.application.name=spring-core-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/aeroops
spring.datasource.username=postgres
spring.datasource.password=860540
spring.jpa.hibernate.ddl-auto=create